debug: true

build:
  image: gcc:4.8
  environment:
  commands:
    - docker build -t fracting/msys2-docker .

notify:
  irc:
    prefix: build
    nick: drone
    channel: wine-zh
    server:
      host: irc.oftc.net
      port: 6667
